(cl:defpackage rosjava_custom_srv-msg
  (:use )
  (:export
   "<ACTIONGOALMSG>"
   "ACTIONGOALMSG"
   "<ACTIONRESULTMSG>"
   "ACTIONRESULTMSG"
   "<ACTIONSTATE>"
   "ACTIONSTATE"
   "<ARMACTION>"
   "ARMACTION"
   "<MAINSERVICEREQUEST>"
   "MAINSERVICEREQUEST"
   "<MONITOR>"
   "MONITOR"
   "<MONITORSERVICEREQUEST>"
   "MONITORSERVICEREQUEST"
   "<MONITORSERVICERESPONSE>"
   "MONITORSERVICERESPONSE"
   "<QUERYSERVICEREQUEST>"
   "QUERYSERVICEREQUEST"
   "<QUERYSERVICERESPONSE>"
   "QUERYSERVICERESPONSE"
  ))

