// Generated by gencpp from file rosjava_custom_srv/PathService.msg
// DO NOT EDIT!


#ifndef ROSJAVA_CUSTOM_SRV_MESSAGE_PATHSERVICE_H
#define ROSJAVA_CUSTOM_SRV_MESSAGE_PATHSERVICE_H

#include <ros/service_traits.h>


#include <rosjava_custom_srv/PathServiceRequest.h>
#include <rosjava_custom_srv/PathServiceResponse.h>


namespace rosjava_custom_srv
{

struct PathService
{

typedef PathServiceRequest Request;
typedef PathServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathService
} // namespace rosjava_custom_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosjava_custom_srv::PathService > {
  static const char* value()
  {
    return "61cc47e6afd1df5f5d0b4911e9fe1a32";
  }

  static const char* value(const ::rosjava_custom_srv::PathService&) { return value(); }
};

template<>
struct DataType< ::rosjava_custom_srv::PathService > {
  static const char* value()
  {
    return "rosjava_custom_srv/PathService";
  }

  static const char* value(const ::rosjava_custom_srv::PathService&) { return value(); }
};


// service_traits::MD5Sum< ::rosjava_custom_srv::PathServiceRequest> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PathService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PathServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PathService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PathServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PathServiceRequest> should match 
// service_traits::DataType< ::rosjava_custom_srv::PathService > 
template<>
struct DataType< ::rosjava_custom_srv::PathServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PathService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PathServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosjava_custom_srv::PathServiceResponse> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PathService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PathServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PathService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PathServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PathServiceResponse> should match 
// service_traits::DataType< ::rosjava_custom_srv::PathService > 
template<>
struct DataType< ::rosjava_custom_srv::PathServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PathService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PathServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSJAVA_CUSTOM_SRV_MESSAGE_PATHSERVICE_H
