// Generated by gencpp from file rosjava_custom_srv/PosesService.msg
// DO NOT EDIT!


#ifndef ROSJAVA_CUSTOM_SRV_MESSAGE_POSESSERVICE_H
#define ROSJAVA_CUSTOM_SRV_MESSAGE_POSESSERVICE_H

#include <ros/service_traits.h>


#include <rosjava_custom_srv/PosesServiceRequest.h>
#include <rosjava_custom_srv/PosesServiceResponse.h>


namespace rosjava_custom_srv
{

struct PosesService
{

typedef PosesServiceRequest Request;
typedef PosesServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PosesService
} // namespace rosjava_custom_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosjava_custom_srv::PosesService > {
  static const char* value()
  {
    return "a243938bf0823a529017bbe4350d96b8";
  }

  static const char* value(const ::rosjava_custom_srv::PosesService&) { return value(); }
};

template<>
struct DataType< ::rosjava_custom_srv::PosesService > {
  static const char* value()
  {
    return "rosjava_custom_srv/PosesService";
  }

  static const char* value(const ::rosjava_custom_srv::PosesService&) { return value(); }
};


// service_traits::MD5Sum< ::rosjava_custom_srv::PosesServiceRequest> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PosesService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PosesServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PosesService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PosesServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PosesServiceRequest> should match 
// service_traits::DataType< ::rosjava_custom_srv::PosesService > 
template<>
struct DataType< ::rosjava_custom_srv::PosesServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PosesService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PosesServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosjava_custom_srv::PosesServiceResponse> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PosesService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PosesServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PosesService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PosesServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PosesServiceResponse> should match 
// service_traits::DataType< ::rosjava_custom_srv::PosesService > 
template<>
struct DataType< ::rosjava_custom_srv::PosesServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PosesService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PosesServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSJAVA_CUSTOM_SRV_MESSAGE_POSESSERVICE_H
