// Generated by gencpp from file rosjava_custom_srv/PoseService.msg
// DO NOT EDIT!


#ifndef ROSJAVA_CUSTOM_SRV_MESSAGE_POSESERVICE_H
#define ROSJAVA_CUSTOM_SRV_MESSAGE_POSESERVICE_H

#include <ros/service_traits.h>


#include <rosjava_custom_srv/PoseServiceRequest.h>
#include <rosjava_custom_srv/PoseServiceResponse.h>


namespace rosjava_custom_srv
{

struct PoseService
{

typedef PoseServiceRequest Request;
typedef PoseServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseService
} // namespace rosjava_custom_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosjava_custom_srv::PoseService > {
  static const char* value()
  {
    return "acd11f6a539565b51de4cb0861b94f97";
  }

  static const char* value(const ::rosjava_custom_srv::PoseService&) { return value(); }
};

template<>
struct DataType< ::rosjava_custom_srv::PoseService > {
  static const char* value()
  {
    return "rosjava_custom_srv/PoseService";
  }

  static const char* value(const ::rosjava_custom_srv::PoseService&) { return value(); }
};


// service_traits::MD5Sum< ::rosjava_custom_srv::PoseServiceRequest> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PoseService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PoseServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PoseService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PoseServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PoseServiceRequest> should match 
// service_traits::DataType< ::rosjava_custom_srv::PoseService > 
template<>
struct DataType< ::rosjava_custom_srv::PoseServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PoseService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PoseServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosjava_custom_srv::PoseServiceResponse> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PoseService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PoseServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PoseService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PoseServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PoseServiceResponse> should match 
// service_traits::DataType< ::rosjava_custom_srv::PoseService > 
template<>
struct DataType< ::rosjava_custom_srv::PoseServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PoseService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PoseServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSJAVA_CUSTOM_SRV_MESSAGE_POSESERVICE_H
