// Generated by gencpp from file rosjava_custom_srv/PredicateService.msg
// DO NOT EDIT!


#ifndef ROSJAVA_CUSTOM_SRV_MESSAGE_PREDICATESERVICE_H
#define ROSJAVA_CUSTOM_SRV_MESSAGE_PREDICATESERVICE_H

#include <ros/service_traits.h>


#include <rosjava_custom_srv/PredicateServiceRequest.h>
#include <rosjava_custom_srv/PredicateServiceResponse.h>


namespace rosjava_custom_srv
{

struct PredicateService
{

typedef PredicateServiceRequest Request;
typedef PredicateServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredicateService
} // namespace rosjava_custom_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosjava_custom_srv::PredicateService > {
  static const char* value()
  {
    return "aedf4a39ef72018907356ccb3fd7b3f3";
  }

  static const char* value(const ::rosjava_custom_srv::PredicateService&) { return value(); }
};

template<>
struct DataType< ::rosjava_custom_srv::PredicateService > {
  static const char* value()
  {
    return "rosjava_custom_srv/PredicateService";
  }

  static const char* value(const ::rosjava_custom_srv::PredicateService&) { return value(); }
};


// service_traits::MD5Sum< ::rosjava_custom_srv::PredicateServiceRequest> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PredicateService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PredicateServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PredicateService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PredicateServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PredicateServiceRequest> should match 
// service_traits::DataType< ::rosjava_custom_srv::PredicateService > 
template<>
struct DataType< ::rosjava_custom_srv::PredicateServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PredicateService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PredicateServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosjava_custom_srv::PredicateServiceResponse> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::PredicateService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::PredicateServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::PredicateService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PredicateServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::PredicateServiceResponse> should match 
// service_traits::DataType< ::rosjava_custom_srv::PredicateService > 
template<>
struct DataType< ::rosjava_custom_srv::PredicateServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::PredicateService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::PredicateServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSJAVA_CUSTOM_SRV_MESSAGE_PREDICATESERVICE_H
