// Generated by gencpp from file rosjava_custom_srv/QueryServiceRequest.msg
// DO NOT EDIT!


#ifndef ROSJAVA_CUSTOM_SRV_MESSAGE_QUERYSERVICEREQUEST_H
#define ROSJAVA_CUSTOM_SRV_MESSAGE_QUERYSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosjava_custom_srv
{
template <class ContainerAllocator>
struct QueryServiceRequest_
{
  typedef QueryServiceRequest_<ContainerAllocator> Type;

  QueryServiceRequest_()
    : query()
    , manager()  {
    }
  QueryServiceRequest_(const ContainerAllocator& _alloc)
    : query(_alloc)
    , manager(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _query_type;
  _query_type query;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _manager_type;
  _manager_type manager;





  typedef boost::shared_ptr< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryServiceRequest_

typedef ::rosjava_custom_srv::QueryServiceRequest_<std::allocator<void> > QueryServiceRequest;

typedef boost::shared_ptr< ::rosjava_custom_srv::QueryServiceRequest > QueryServiceRequestPtr;
typedef boost::shared_ptr< ::rosjava_custom_srv::QueryServiceRequest const> QueryServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosjava_custom_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rosjava_custom_srv': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/rosjava_custom_srv/msg'], 'actionlib_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/common_msgs/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/devel/share/moveit_msgs/msg', '/home/test/Downloads/190816_cmtm_code/catkin_ws/src/moveit_msgs/msg'], 'trajectory_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/common_msgs/trajectory_msgs/msg'], 'sensor_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/common_msgs/sensor_msgs/msg'], 'shape_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/common_msgs/shape_msgs/msg'], 'octomap_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/octomap_msgs/msg'], 'object_recognition_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/devel/share/object_recognition_msgs/msg', '/home/test/Downloads/190816_cmtm_code/catkin_ws/src/object_recognition_msgs/msg'], 'geometry_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/common_msgs/geometry_msgs/msg'], 'vision_msgs': ['/home/test/Downloads/190816_cmtm_code/catkin_ws/src/vision_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c87ac28ec8f021755cccae1836d04e07";
  }

  static const char* value(const ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc87ac28ec8f02175ULL;
  static const uint64_t static_value2 = 0x5cccae1836d04e07ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosjava_custom_srv/QueryServiceRequest";
  }

  static const char* value(const ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string query\n\
string manager\n\
";
  }

  static const char* value(const ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query);
      stream.next(m.manager);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosjava_custom_srv::QueryServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "query: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.query);
    s << indent << "manager: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.manager);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSJAVA_CUSTOM_SRV_MESSAGE_QUERYSERVICEREQUEST_H
